import {
  Briefcase,
  Heart,
  Palette,
  Scale,
  Stethoscope,
  Settings,
  DollarSign,
  GraduationCap,
  ShoppingBag,
  Radio,
  Megaphone,
  Lightbulb,
  Home,
  Users,
  UserCheck,
  Headphones,
  Church,
  TrendingUp,
  Phone,
  Monitor,
  ClipboardList,
  Building2,
  Utensils,
  Plane,
  Car,
  Leaf,
  Dumbbell,
  Music,
  Camera,
  Gamepad2,
  Shield,
  Truck,
  FileCheck,
  Award,
  FileText,
  CheckCircle,
  MoreHorizontal,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface Subcategory {
  id: string;
  label: string;
}

export interface Category {
  id: string;
  label: string;
  icon: LucideIcon;
  description: string;
  subcategories: Subcategory[];
}

export const categories: Category[] = [
  {
    id: "executive",
    label: "Executive Management",
    icon: Briefcase,
    description: "To provide strategic direction and oversee the overall operations of the organization.",
    subcategories: [
      { id: "ceo", label: "Chief Executive Officer (CEO)" },
      { id: "coo", label: "Chief Operating Officer (COO)" },
      { id: "cfo", label: "Chief Financial Officer (CFO)" },
      { id: "cto", label: "Chief Technology Officer (CTO)" },
      { id: "cmo", label: "Chief Marketing Officer (CMO)" },
      { id: "chro", label: "Chief Human Resources Officer (CHRO)" },
      { id: "ciso", label: "Chief Information Security Officer (CISO)" },
      { id: "cso", label: "Chief Strategy Officer (CSO)" },
    ],
  },
  {
    id: "customer_success",
    label: "Customer Success",
    icon: Heart,
    description: "To ensure customer satisfaction and retention by providing support, guidance, and solutions.",
    subcategories: [
      { id: "account_manager", label: "Account Manager" },
      { id: "onboarding_specialist", label: "Onboarding Specialist" },
      { id: "cs_manager", label: "Customer Success Manager" },
      { id: "cs_coordinator", label: "Customer Success Coordinator" },
      { id: "cs_analyst", label: "Customer Success Analyst" },
    ],
  },
  {
    id: "creative",
    label: "Creative",
    icon: Palette,
    description: "Responsible for generating innovative and visually appealing content, designs, and ideas.",
    subcategories: [
      { id: "art_director", label: "Art Director" },
      { id: "video_editor", label: "Video Editor" },
      { id: "web_designer", label: "Web Designer" },
      { id: "graphic_designer", label: "Graphic Designer" },
      { id: "ux_designer", label: "UX Designer" },
      { id: "illustrator", label: "Illustrator" },
      { id: "animator", label: "Animator" },
    ],
  },
  {
    id: "legal",
    label: "Legal",
    icon: Scale,
    description: "To provide legal advice and representation, ensuring compliance with laws and regulations.",
    subcategories: [
      { id: "securities_lawyer", label: "Securities Lawyer" },
      { id: "personal_lawyer", label: "Personal Lawyer" },
      { id: "family_lawyer", label: "Family Lawyer" },
      { id: "criminal_defense_lawyer", label: "Criminal Defense Lawyer" },
      { id: "real_estate_lawyer", label: "Real Estate Lawyer" },
      { id: "trust_estates_lawyer", label: "Trust And Estates Lawyer" },
      { id: "civil_rights_lawyer", label: "Civil Rights Lawyer" },
      { id: "bankruptcy_lawyer", label: "Bankruptcy Lawyer" },
      { id: "immigration_lawyer", label: "Immigration Lawyer" },
      { id: "paralegal", label: "Paralegal" },
      { id: "ip_lawyer", label: "Intellectual Property Lawyer" },
      { id: "employment_lawyer", label: "Employment Lawyer" },
      { id: "tax_lawyer", label: "Tax Lawyer" },
      { id: "corporate_lawyer", label: "Corporate Lawyer" },
    ],
  },
  {
    id: "medical",
    label: "Medical",
    icon: Stethoscope,
    description: "Responsible for providing healthcare services and ensuring the well-being of individuals.",
    subcategories: [
      { id: "registered_nurse", label: "Registered Nurse" },
      { id: "obgyn", label: "Obstetrician-Gynecologist (OB-GYN)" },
      { id: "family_doctor", label: "Family Doctor" },
      { id: "pediatrician", label: "Pediatrician" },
      { id: "counseling_psychologist", label: "Counseling Psychologist" },
      { id: "physical_therapist", label: "Physical Therapist" },
      { id: "pharmacist", label: "Pharmacist" },
      { id: "physician", label: "Physician" },
      { id: "dentist", label: "Dentist" },
      { id: "chiropractor", label: "Chiropractor" },
      { id: "psychiatrist", label: "Psychiatrist" },
      { id: "neurosurgeon", label: "Neurosurgeon" },
      { id: "medical_technologist", label: "Medical Technologist" },
      { id: "clinical_psychologist", label: "Clinical Psychologist" },
      { id: "speech_pathologist", label: "Speech-Language Pathologist" },
      { id: "occupational_therapist", label: "Occupational Therapist" },
      { id: "psychologist", label: "Psychologist" },
      { id: "dietitian", label: "Dietitian" },
    ],
  },
  {
    id: "engineering",
    label: "Engineering",
    icon: Settings,
    description: "Design, develop, and improve products, processes, and systems using scientific and mathematical principles.",
    subcategories: [
      { id: "software_engineer", label: "Software Engineer" },
      { id: "civil_engineer", label: "Civil Engineer" },
      { id: "mechanical_engineer", label: "Mechanical Engineer" },
      { id: "electrical_engineer", label: "Electrical Engineer" },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    icon: DollarSign,
    description: "To manage an organization's financial resources, including budgeting, forecasting, accounting, and reporting.",
    subcategories: [
      { id: "accountant", label: "Accountant" },
      { id: "accounts_receivable", label: "Accounts Receivable Specialist" },
      { id: "accounts_payable", label: "Accounts Payable Specialist" },
      { id: "financial_planner", label: "Financial Planner" },
      { id: "financial_analyst", label: "Financial Analyst" },
      { id: "cfo", label: "Chief Financial Officer (CFO)" },
    ],
  },
  {
    id: "education",
    label: "Education",
    icon: GraduationCap,
    description: "To provide learning opportunities and facilitate the acquisition of knowledge and skills.",
    subcategories: [
      { id: "teacher", label: "Teacher" },
      { id: "curriculum_developer", label: "Curriculum Developer" },
      { id: "professor", label: "Professor" },
      { id: "tutor", label: "Tutor" },
    ],
  },
  {
    id: "retail",
    label: "Retail",
    icon: ShoppingBag,
    description: "To manage the buying, merchandising, and sales of products or services to customers.",
    subcategories: [
      { id: "assistant_store_manager", label: "Assistant Store Manager" },
      { id: "retail_buyer", label: "Retail Buyer" },
      { id: "store_operations_manager", label: "Store Operations Manager" },
      { id: "store_manager", label: "Store Manager" },
      { id: "department_manager", label: "Department Manager" },
      { id: "district_manager", label: "District Or Regional Manager" },
      { id: "inventory_specialist", label: "Inventory Specialist" },
      { id: "visual_merchandiser", label: "Visual Merchandiser" },
      { id: "sales_associate", label: "Sales Associate" },
    ],
  },
  {
    id: "media",
    label: "Media & Communications",
    icon: Radio,
    description: "To manage and promote the organization's messaging, brand, and public image through various media channels.",
    subcategories: [
      { id: "content_writer", label: "Content Writer" },
      { id: "journalist", label: "Journalist" },
      { id: "pr_specialist", label: "Public Relations Specialist" },
    ],
  },
  {
    id: "public_relations",
    label: "Public Relations",
    icon: Megaphone,
    description: "Responsible for managing the communication and reputation of an organization with the public and media.",
    subcategories: [
      { id: "pr_specialist", label: "PR Specialist" },
      { id: "crisis_manager", label: "Crisis Communications Manager" },
      { id: "social_media_strategist", label: "Social Media Strategist" },
      { id: "pr_manager", label: "PR Manager" },
    ],
  },
  {
    id: "entrepreneur",
    label: "Entrepreneur",
    icon: Lightbulb,
    description: "The role of an Entrepreneur at an organization is to create and develop new business opportunities, products, or services.",
    subcategories: [
      { id: "startup_advisor", label: "Startup Advisor" },
      { id: "founder", label: "Founder" },
      { id: "cmo", label: "Chief Marketing Officer (CMO)" },
      { id: "cto", label: "Chief Technology Officer (CTO)" },
      { id: "coo", label: "Chief Operating Officer (COO)" },
      { id: "cso", label: "Chief Strategy Officer (CSO)" },
      { id: "ceo", label: "Chief Executive Officer (CEO)" },
      { id: "chro", label: "Chief Human Resources Officer (CHRO)" },
      { id: "cfo", label: "Chief Financial Officer (CFO)" },
      { id: "ciso", label: "Chief Information Security Officer (CISO)" },
    ],
  },
  {
    id: "real_estate",
    label: "Real Estate",
    icon: Home,
    description: "Managing and overseeing the buying, selling, leasing, and development of property for the organization.",
    subcategories: [
      { id: "leasing_agent", label: "Leasing Agent" },
      { id: "real_estate_analyst", label: "Real Estate Analyst" },
      { id: "mortgage_loan_officer", label: "Mortgage Loan Officer" },
      { id: "real_estate_developer", label: "Real Estate Developer" },
      { id: "property_manager", label: "Property Manager" },
      { id: "real_estate_broker", label: "Real Estate Broker" },
      { id: "real_estate_investor", label: "Real Estate Investor" },
      { id: "mortgage_broker", label: "Mortgage Broker" },
      { id: "real_estate_appraiser", label: "Real Estate Appraiser" },
      { id: "real_estate_agent", label: "Real Estate Agent" },
    ],
  },
  {
    id: "hr",
    label: "Human Resources",
    icon: Users,
    description: "Managing and supporting the organization's employees, including recruitment, hiring, training, benefits, and employee relations.",
    subcategories: [
      { id: "recruiter", label: "Recruiter" },
      { id: "employee_relations", label: "Employee Relations Specialist" },
      { id: "hris_specialist", label: "HRIS Specialist" },
      { id: "compensation_benefits", label: "Compensation And Benefits Specialist" },
      { id: "training_development", label: "Training And Development Specialist" },
      { id: "hr_analyst", label: "HR Analyst" },
      { id: "hr_manager", label: "HR Manager" },
      { id: "chro", label: "Chief Human Resources Officer (CHRO)" },
    ],
  },
  {
    id: "personal_dev",
    label: "Personal Development",
    icon: UserCheck,
    description: "Focused on helping individuals improve their personal and professional skills.",
    subcategories: [
      { id: "life_coach", label: "Life Coach" },
      { id: "career_coach", label: "Career Coach" },
      { id: "mindset_coach", label: "Mindset Coach" },
      { id: "productivity_coach", label: "Productivity Coach" },
      { id: "wellness_coach", label: "Wellness Coach" },
    ],
  },
  {
    id: "customer_service",
    label: "Customer Service",
    icon: Headphones,
    description: "Providing assistance and support to customers before, during, and after their purchase to ensure satisfaction.",
    subcategories: [
      { id: "technical_support", label: "Technical Support Specialist" },
      { id: "cs_team_lead", label: "Customer Service Team Lead" },
      { id: "cs_rep", label: "Customer Service Rep" },
      { id: "call_center_agent", label: "Call Center Agent" },
    ],
  },
  {
    id: "religious",
    label: "Religious Services",
    icon: Church,
    description: "Providing spiritual guidance and support to members of a religious community.",
    subcategories: [
      { id: "priest", label: "Priest" },
      { id: "religious_educator", label: "Religious Educator" },
      { id: "youth_minister", label: "Youth Minister" },
      { id: "imam", label: "Imam" },
      { id: "rabbi", label: "Rabbi" },
    ],
  },
  {
    id: "marketing",
    label: "Marketing",
    icon: TrendingUp,
    description: "Promoting and advertising products or services to increase sales and revenue.",
    subcategories: [
      { id: "marketing_analyst", label: "Marketing Analyst" },
      { id: "event_marketing", label: "Event Marketing Specialist" },
      { id: "ecommerce_manager", label: "E-Commerce Manager" },
      { id: "seo_specialist", label: "SEO Specialist" },
      { id: "social_media_manager", label: "Social Media Manager" },
      { id: "ppc_specialist", label: "PPC Specialist" },
      { id: "digital_marketer", label: "Digital Marketing Specialist" },
      { id: "amazon_fba", label: "Amazon FBA Ecommerce Manager" },
      { id: "influencer_marketing", label: "Influencer Marketing Specialist" },
      { id: "lead_generation", label: "Lead Generation Specialist" },
      { id: "b2b_marketing", label: "B2B Marketing Specialist" },
      { id: "paid_social", label: "Paid Social Media Specialist" },
      { id: "b2b_content", label: "B2B Content Marketing Manager" },
      { id: "abm_manager", label: "Account-Based Marketing Manager" },
      { id: "product_marketing", label: "Product Marketing Manager" },
      { id: "creative_strategist", label: "Creative Strategist" },
      { id: "brand_manager", label: "Brand Manager" },
      { id: "marketing_manager", label: "Marketing Manager" },
      { id: "email_marketing", label: "Email Marketing Specialist" },
      { id: "content_marketing", label: "Content Marketing Specialist" },
      { id: "marketing_coordinator", label: "Marketing Coordinator" },
      { id: "market_research", label: "Market Research Analyst" },
      { id: "copywriter", label: "Copywriter" },
      { id: "marketing_operations", label: "Marketing Operations" },
      { id: "content_creator", label: "Content Creator" },
      { id: "cmo", label: "Chief Marketing Officer (CMO)" },
    ],
  },
  {
    id: "sales",
    label: "Sales",
    icon: Phone,
    description: "Generating revenue by selling products or services to customers.",
    subcategories: [
      { id: "sales_engineer", label: "Sales Engineer" },
      { id: "sales_manager", label: "Sales Manager" },
      { id: "inside_sales", label: "Inside Sales Representative" },
      { id: "outside_sales", label: "Outside Sales Representative" },
      { id: "business_dev_manager", label: "Business Development Manager" },
      { id: "sdr", label: "Sales Development Representative" },
      { id: "account_executive", label: "Account Executive" },
      { id: "sales_analyst", label: "Sales Analyst" },
      { id: "sales_operations", label: "Sales Operations" },
    ],
  },
  {
    id: "it",
    label: "Information Technology",
    icon: Monitor,
    description: "To manage and maintain technology systems and infrastructure to support the organization's operations and goals.",
    subcategories: [
      { id: "ciso", label: "Chief Information Security Officer (CISO)" },
      { id: "it_manager", label: "IT Manager" },
      { id: "cto", label: "Chief Technology Officer (CTO)" },
      { id: "system_admin", label: "Systems Administrator" },
    ],
  },
  {
    id: "administrative",
    label: "Administrative",
    icon: ClipboardList,
    description: "To manage and support the day-to-day operations of the organization, including tasks such as record-keeping, scheduling, communication, and resource management.",
    subcategories: [
      { id: "executive_assistant", label: "Executive Assistant" },
      { id: "office_manager", label: "Office Manager" },
      { id: "data_entry_clerk", label: "Data Entry Clerk" },
      { id: "receptionist", label: "Receptionist" },
      { id: "admin_assistant", label: "Administrative Assistant" },
    ],
  },
  {
    id: "hospitality",
    label: "Hospitality",
    icon: Building2,
    description: "Providing excellent service and experiences to guests in hotels, resorts, and events.",
    subcategories: [
      { id: "hotel_manager", label: "Hotel Manager" },
      { id: "concierge", label: "Concierge" },
      { id: "event_planner", label: "Event Planner" },
      { id: "front_desk", label: "Front Desk" },
      { id: "housekeeping_manager", label: "Housekeeping Manager" },
    ],
  },
  {
    id: "food_beverage",
    label: "Food & Beverage",
    icon: Utensils,
    description: "Managing food service operations and culinary experiences.",
    subcategories: [
      { id: "chef", label: "Chef" },
      { id: "restaurant_manager", label: "Restaurant Manager" },
      { id: "barista", label: "Barista" },
      { id: "sommelier", label: "Sommelier" },
      { id: "food_critic", label: "Food Critic" },
    ],
  },
  {
    id: "travel",
    label: "Travel & Tourism",
    icon: Plane,
    description: "Facilitating travel experiences and tourism services.",
    subcategories: [
      { id: "travel_agent", label: "Travel Agent" },
      { id: "tour_guide", label: "Tour Guide" },
      { id: "flight_attendant", label: "Flight Attendant" },
      { id: "tourism_director", label: "Tourism Director" },
      { id: "travel_blogger", label: "Travel Blogger" },
    ],
  },
  {
    id: "automotive",
    label: "Automotive",
    icon: Car,
    description: "Services related to vehicles, maintenance, and automotive sales.",
    subcategories: [
      { id: "mechanic", label: "Mechanic" },
      { id: "car_sales", label: "Car Sales" },
      { id: "service_advisor", label: "Service Advisor" },
      { id: "auto_parts", label: "Auto Parts Specialist" },
      { id: "fleet_manager", label: "Fleet Manager" },
    ],
  },
  {
    id: "agriculture",
    label: "Agriculture",
    icon: Leaf,
    description: "Farming, livestock, and agricultural consulting services.",
    subcategories: [
      { id: "farmer", label: "Farmer" },
      { id: "agronomist", label: "Agronomist" },
      { id: "agricultural_consultant", label: "Agricultural Consultant" },
      { id: "livestock_manager", label: "Livestock Manager" },
      { id: "farm_equipment", label: "Farm Equipment Specialist" },
    ],
  },
  {
    id: "fitness",
    label: "Fitness & Sports",
    icon: Dumbbell,
    description: "Health, fitness, and athletic training services.",
    subcategories: [
      { id: "personal_trainer", label: "Personal Trainer" },
      { id: "sports_coach", label: "Sports Coach" },
      { id: "gym_manager", label: "Gym Manager" },
      { id: "yoga_instructor", label: "Yoga Instructor" },
      { id: "physical_therapist", label: "Physical Therapist" },
    ],
  },
  {
    id: "entertainment",
    label: "Entertainment",
    icon: Music,
    description: "Music, acting, and entertainment industry services.",
    subcategories: [
      { id: "musician", label: "Musician" },
      { id: "actor", label: "Actor" },
      { id: "producer", label: "Producer" },
      { id: "dj", label: "DJ" },
      { id: "talent_manager", label: "Talent Manager" },
    ],
  },
  {
    id: "photography",
    label: "Photography & Video",
    icon: Camera,
    description: "Visual media creation and production services.",
    subcategories: [
      { id: "photographer", label: "Photographer" },
      { id: "videographer", label: "Videographer" },
      { id: "photo_editor", label: "Photo Editor" },
      { id: "cinematographer", label: "Cinematographer" },
      { id: "drone_operator", label: "Drone Operator" },
    ],
  },
  {
    id: "gaming",
    label: "Gaming & Esports",
    icon: Gamepad2,
    description: "Video game development and competitive gaming.",
    subcategories: [
      { id: "game_developer", label: "Game Developer" },
      { id: "streamer", label: "Streamer" },
      { id: "esports_player", label: "Esports Player" },
      { id: "game_designer", label: "Game Designer" },
      { id: "community_manager", label: "Community Manager" },
    ],
  },
  {
    id: "safety_k3",
    label: "Safety (K3)",
    icon: Shield,
    description: "Keselamatan dan Kesehatan Kerja (K3) untuk memastikan lingkungan kerja yang aman dan sehat.",
    subcategories: [
      { id: "safety_officer", label: "Safety Officer" },
      { id: "hse_manager", label: "HSE Manager" },
      { id: "k3_specialist", label: "K3 Specialist" },
      { id: "safety_inspector", label: "Safety Inspector" },
      { id: "fire_safety", label: "Fire Safety Officer" },
      { id: "ohs_consultant", label: "OHS Consultant" },
      { id: "safety_trainer", label: "Safety Trainer" },
      { id: "emergency_response", label: "Emergency Response Coordinator" },
    ],
  },
  {
    id: "supply_chain",
    label: "Rantai Pasok (Logistik)",
    icon: Truck,
    description: "Mengelola aliran barang, informasi, dan sumber daya dari pemasok ke pelanggan.",
    subcategories: [
      { id: "supply_chain_manager", label: "Supply Chain Manager" },
      { id: "logistics_coordinator", label: "Logistics Coordinator" },
      { id: "warehouse_manager", label: "Warehouse Manager" },
      { id: "procurement_specialist", label: "Procurement Specialist" },
      { id: "inventory_controller", label: "Inventory Controller" },
      { id: "distribution_manager", label: "Distribution Manager" },
      { id: "fleet_coordinator", label: "Fleet Coordinator" },
      { id: "import_export", label: "Import/Export Specialist" },
    ],
  },
  {
    id: "licensing",
    label: "Perijinan & Sertifikasi Usaha",
    icon: FileCheck,
    description: "Mengurus perizinan usaha, sertifikasi, dan kepatuhan regulasi bisnis.",
    subcategories: [
      { id: "licensing_specialist", label: "Licensing Specialist" },
      { id: "permit_coordinator", label: "Permit Coordinator" },
      { id: "compliance_officer", label: "Compliance Officer" },
      { id: "regulatory_affairs", label: "Regulatory Affairs Specialist" },
      { id: "business_registration", label: "Business Registration Consultant" },
      { id: "legal_compliance", label: "Legal Compliance Advisor" },
      { id: "siup_specialist", label: "SIUP/NIB Specialist" },
      { id: "environmental_permit", label: "Environmental Permit Consultant" },
    ],
  },
  {
    id: "competency",
    label: "Sertifikasi & Pengembangan Kompetensi",
    icon: Award,
    description: "Pengembangan kompetensi karyawan melalui sertifikasi dan pelatihan profesional.",
    subcategories: [
      { id: "competency_assessor", label: "Competency Assessor" },
      { id: "training_manager", label: "Training Manager" },
      { id: "certification_specialist", label: "Certification Specialist" },
      { id: "lsp_coordinator", label: "LSP Coordinator" },
      { id: "bnsp_assessor", label: "BNSP Assessor" },
      { id: "skill_development", label: "Skill Development Specialist" },
      { id: "learning_designer", label: "Learning Designer" },
      { id: "competency_mapper", label: "Competency Mapper" },
    ],
  },
  {
    id: "tender",
    label: "Tender",
    icon: FileText,
    description: "Proses pengadaan barang dan jasa melalui tender dan lelang.",
    subcategories: [
      { id: "tender_specialist", label: "Tender Specialist" },
      { id: "bid_manager", label: "Bid Manager" },
      { id: "procurement_analyst", label: "Procurement Analyst" },
      { id: "contract_specialist", label: "Contract Specialist" },
      { id: "vendor_manager", label: "Vendor Manager" },
      { id: "proposal_writer", label: "Proposal Writer" },
      { id: "lpse_specialist", label: "LPSE Specialist" },
      { id: "tender_evaluator", label: "Tender Evaluator" },
    ],
  },
  {
    id: "iso_management",
    label: "Manajemen ISO",
    icon: CheckCircle,
    description: "Implementasi dan pengelolaan sistem manajemen berstandar ISO.",
    subcategories: [
      { id: "iso_consultant", label: "ISO Consultant" },
      { id: "quality_manager", label: "Quality Manager" },
      { id: "internal_auditor", label: "Internal Auditor" },
      { id: "document_controller", label: "Document Controller" },
      { id: "iso_9001", label: "ISO 9001 Specialist (Manajemen Mutu)" },
      { id: "iso_14001", label: "ISO 14001 Specialist (Manajemen Lingkungan)" },
      { id: "iso_45001", label: "ISO 45001 Specialist (K3)" },
      { id: "iso_27001", label: "ISO 27001 Specialist (Keamanan Informasi)" },
      { id: "iso_37001", label: "ISO 37001:2016 Specialist (Sistem Manajemen Anti Penyuapan)" },
      { id: "iso_22000", label: "ISO 22000 Specialist (Keamanan Pangan)" },
      { id: "qms_coordinator", label: "QMS Coordinator" },
      { id: "integrated_management", label: "Integrated Management System Specialist" },
    ],
  },
  {
    id: "others",
    label: "Lainnya",
    icon: MoreHorizontal,
    description: "Kategori lain yang tidak termasuk dalam kategori utama.",
    subcategories: [
      { id: "general_assistant", label: "General Assistant" },
      { id: "custom_role", label: "Custom Role" },
      { id: "multi_purpose", label: "Multi-Purpose Assistant" },
      { id: "specialist", label: "Specialist" },
      { id: "consultant", label: "Consultant" },
      { id: "advisor", label: "Advisor" },
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function getSubcategoryLabel(categoryId: string, subcategoryId: string): string {
  const category = getCategoryById(categoryId);
  if (!category) return subcategoryId;
  const sub = category.subcategories.find((s) => s.id === subcategoryId);
  return sub?.label || subcategoryId;
}
